const zodiac = [

    {
        zodiacname: "Aries",
        symbol: "Ram",
        element: "Fire",
        color: "Red",
        Day: "Tuesday",
        Ruler: "Mars",
        compatibility: "Libra, Leo",
        luckyNumbers: "1,8, 17",
        strengths: "Courageous, determined, confident, enthusiastic, optimistic, honest, passionate",
        weaknesses: "Impatient, moody, short-tempered, impulsive, aggressive",
        likes: "Comfortable clothes, taking on leadership roles, physical challenges, individual sports",
        dislikes: "Inactivity, delays, work that does not use one's talents",
		picture: "https://www.astrology-zodiac-signs.com/images/aries.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/aries/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/aries/",
        sumary: "As the first sign in the zodiac, the presence of Aries always marks the beginning of something energetic and turbulent. They are continuously looking for dynamic, speed and competition, always being the first in everything - from work to social gatherings. Thanks to its ruling planet Mars and the fact it belongs to the element of Fire (just like Leo and Sagittarius), Aries is one of the most active zodiac signs. It is in their nature to take action, sometimes before they think about it well.",
		zodiacId: "1"
    },

    {
        zodiacname: "Taurus",
        symbol: "Bull",
        element: "Earth",
        color: "Green, Pink",
        Day: "Friday",
        Ruler: "Venus",
        compatibility: "Scorpio, Cancer",
        luckyNumbers: "2, 6, 9, 12, 24",
        strengths: "Reliable, patient, practical, devoted, responsible, stable",
        weaknesses: "Stubborn, possessive, uncompromising",
        likes: "Gardening, cooking, music, romance, high quality clothes, working with hands",
        dislikes: "Sudden changes, complications, insecurity of any kind, synthetic fabrics",
		picture: "https://www.astrology-zodiac-signs.com/images/taurus.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodia-signs/taurus.jpg",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/taurus/",
        sumary: "Practical and well-grounded, Taurus is the sign that harvests the fruits of labor. They feel the need to always be surrounded by love and beauty, turned to the material world, hedonism, and physical pleasures. People born with their Sun in Taurus are sensual and tactile, considering touch and taste the most important of all senses. Stable and conservative, this is one of the most reliable signs of the zodiac, ready to endure and stick to their choices until they reach the point of personal satisfaction.",
		zodiacId: "2"
    },
    {
        zodiacname: "Gemini",
        symbol: "",
        element: "Air",
        color: "Light-Green, Yellow",
        Day: "Wednesday",
        Ruler: "Mecury",
        compatibility: " Sagittarius, Aquarius",
        luckyNumbers: "25, 7, 14, 23",
        strengths: "Gentle, affectionate, curious, adaptable, ability to learn quickly and exchange ideas",
        weaknesses: "Nervous, inconsistent, indecisive",
        likes: "Music, books, magazines, chats with nearly anyone, short trips around the town",
        dislikes: "Being alone, being confined, repetition and routine",
		picture: "https://www.astrology-zodiac-signs.com/images/gemini.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/gemini/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/gemini/",
        sumary: "Expressive and quick-witted, Gemini represents two different personalities in one and you will never be sure which one you will face. They are sociable, communicative and ready for fun, with a tendency to suddenly get serious, thoughtful and restless. They are fascinated with the world itself, extremely curious, with a constant feeling that there is not enough time to experience everything they want to see.",
		zodiacId: "3"
    },
    {
        zodiacname: "Cancer",
        symbol: "Crab",
        element: "Water",
        color: "White",
        Day: "Monday, Thursday",
        Ruler: "Moon",
        compatibility: "Capricorn, Tarus",
        luckyNumbers: "2, 3, 15, 20",
        strengths: "Tenacious, highly imaginative, loyal, emotional, sympathetic, persuasive",
        weaknesses: "Moody, pessimistic, suspicious, manipulative, insecure",
        likes: "Art, home-based hobbies, relaxing near or in water, helping loved ones, a good meal with friends",
        dislikes: "Strangers, any criticism of Mom, revealing of personal life",
		picture: "https://www.astrology-zodiac-signs.com/images/cancer.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/cancer/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/cancer/",
        sumary: "Deeply intuitive and sentimental, Cancer can be one of the most challenging zodiac signs to get to know. They are very emotional and sensitive, and care deeply about matters of the family and their home. Cancer is sympathetic and attached to people they keep close. Those born with their Sun in Cancer are very loyal and able to empathize with other people's pain and suffering.",
		zodiacId: "4"
    },
    {
        zodiacname: "Leo",
        symbol: "Lion",
        element: "Fire",
        color: "Gold, Yellow, Orange",
        Day: "Sunday",
        Ruler: "Sun",
        compatibility: "Aquarius, Gemini",
        luckyNumbers: " 1, 3, 10, 19",
        strengths: "Creative, passionate, generous, warm-hearted, cheerful, humorous",
        weaknesses: "Arrogant, stubborn, self-centered, lazy, inflexible",
        likes: "Theater, taking holidays, being admired, expensive things, bright colors, fun with friends",
        dislikes: "Being ignored, facing difficult reality, not being treated like a king or queen",
		picture: "https://www.astrology-zodiac-signs.com/images/leo.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/leo/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/leo/",
        sumary: "People born under the sign of Leo are natural born leaders. They are dramatic, creative, self-confident, dominant and extremely difficult to resist, able to achieve anything they want to in any area of life they commit to. There is a specific strength to a Leo and their king of the jungle status. Leo often has many friends for they are generous and loyal. Self-confident and attractive, this is a Sun sign capable of uniting different groups of people and leading them as one towards a shared cause, and their healthy sense of humor makes collaboration with other people even easier.",
		zodiacId: "5"
	},
    {
        zodiacname: "Virgo",
        symbol: "Lion",
        element: "Earth",
        color: "Grey, Beige, Pale-Yellow",
        Day: "Wednesday",
        Ruler: "Mercury",
        compatibility: "Pisces, Cancer",
        luckyNumbers: " 5, 14, 15, 23, 32",
        strengths: "Loyal, analytical, kind, hardworking, practical",
        weaknesses: "Shyness, worry, overly critical of self and others, all work and no play",
        likes: "Animals, healthy food, books, nature, cleanliness",
        dislikes: "Rudeness, asking for help, taking center stage",
		picture: "https://www.astrology-zodiac-signs.com/images/virgo.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/virgo/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/virgo/",
        sumary: "Virgos are always paying attention to the smallest details and their deep sense of humanity makes them one of the most careful signs of the zodiac. Their methodical approach to life ensures that nothing is left to chance, and although they are often tender, their heart might be closed for the outer world. This is a sign often misunderstood, not because they lack the ability to express, but because they won’t accept their feelings as valid, true, or even relevant when opposed to reason. The symbolism behind the name speaks well of their nature, born with a feeling they are experiencing everything for the first time.",
		zodiacId: "6"
    },

    {
        zodiacname: "Libra",
        symbol: "Lion",
        element: "Air",
        color: "Pink, Green",
        Day: "Friday",
        Ruler: "Venus",
        compatibility: "Aries, Sagittarius",
        luckyNumbers: " 4, 6, 13, 15, 24",
        strengths: "Cooperative,diplomatic, gracious, fair-minded, social",
        weaknesses: "Indecisive, avoids confrontations, will carry a grudge, self-pity",
        likes: "Harmony, gentleness, sharing with others, the outdoors",
        dislikes: "Violence, injustice, loudmouths, conformity",
		picture: "https://www.astrology-zodiac-signs.com/images/libra.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/libra/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/libra/",
        sumary: "People born under the sign of Libra are peaceful, fair, and they hate being alone. Partnership is very important for them, as their mirror and someone giving them the ability to be the mirror themselves. These individuals are fascinated by balance and symmetry, they are in a constant chase for justice and equality, realizing through life that the only thing that should be truly important to themselves in their own inner core of personality. This is someone ready to do nearly anything to avoid conflict, keeping the peace whenever possible",
		zodiacId: "7"
    },
    {
        zodiacname: "Scorpio",
        symbol: "Lion",
        element: "Water",
        color: "Scarlet, Red, Rust ",
        Day: "Tuesday",
        Ruler: "Pluto, Mars",
        compatibility: "Taurus, Cancer",
        luckyNumbers: " 8, 11, 18, 22",
        strengths: "Resourceful, brave, passionate, stubborn, a true friend",
        weaknesses: "Distrusting, jealous, secretive, violent",
        likes: "Truth, facts, being right, longtime friends, teasing, a grand passion",
        dislikes: "Dishonesty, revealing secrets, passive people",
		picture: "https://www.astrology-zodiac-signs.com/images/scorpio.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/scorpio/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/scorpio/",
        sumary: "Scorpio-born are passionate and assertive people. They are determined and decisive, and will research until they find out the truth. Scorpio is a great leader, always aware of the situation and also features prominently in resourcefulness. Scorpio is a Water sign and lives to experience and express emotions. Although emotions are very important for Scorpio, they manifest them differently than other water signs. In any case, you can be sure that the Scorpio will keep your secrets, whatever they may be.",
		zodiacId: "8"
    },
    {
        zodiacname: "Sagittarius",
        symbol: "",
        element: "Fire",
        color: "Blue",
        Day: "Thursday",
        Ruler: "Jupiter",
        compatibility: "Gemini, Aries",
        luckyNumbers: " 3, 7, 9, 12, 21",
        strengths: "Generous, idealistic, great sense of humor",
        weaknesses: " Promises more than can deliver, very impatient, will say anything no matter how undiplomatic",
        likes: "Freedom, travel, philosophy, being outdoors",
        dislikes: "Clingy people, being constrained, off-the-wall theories, details",
		picture: "https://www.astrology-zodiac-signs.com/images/sagittarius.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/sagittarius/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/sagittarius/",
        sumary: "Curious and energetic, Sagittarius is one of the biggest travelers among all zodiac signs. Their open mind and philosophical view motivates them to wander around the world in search of the meaning of life. Sagittarius is extrovert, optimistic and enthusiastic, and likes changes. Sagittarius-born are able to transform their thoughts into concrete actions and they will do anything to achieve their goals.",
		zodiacId: "9"
    },
    {
        zodiacname: "Capricorn",
        symbol: "Goat",
        element: "Earth",
        color: "Brown, Black",
        Day: "Saturday",
        Ruler: "Saturn",
        compatibility: "Taurus, Cancer",
        luckyNumbers: " 4, 8, 13, 22",
        strengths: " Responsible, disciplined, self-control, good managers",
        weaknesses: " Know-it-all, unforgiving, condescending, expecting the worst",
        likes: " Family, tradition, music, understated status, quality craftsmanship",
        dislikes: "Almost everything at some point",
		picture: "https://www.astrology-zodiac-signs.com/images/capricorn.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/capricorn/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/capricorn/",
        sumary: "Capricorn is a sign that represents time and responsibility, and its representatives are traditional and often very serious by nature. These individuals possess an inner state of independence that enables significant progress both in their personal and professional lives. They are masters of self-control and have the ability to lead the way, make solid and realistic plans, and manage many people who work for them at any time. They will learn from their mistakes and get to the top based solely on their experience and expertise.",
		zodiacId: "10"
    },
    {
        zodiacname: "Aquarius",
        symbol: "Water Barer",
        element: "Air",
        color: "Light-blue, Silver",
        Day: "Saturday",
        Ruler: "Uranus, Saturn",
        compatibility: "Leo, Sagittarius",
        luckyNumbers: "  4, 7, 11, 22, 29",
        strengths: " Progressive, original, independent, humanitarian",
        weaknesses: " Runs from emotional expression, temperamental, uncompromising, aloof",
        likes: "  Fun with friends, helping others, fighting for causes, intellectual conversation, a good listener",
        dislikes: "Limitations, broken promises, being lonely, dull or boring situations, people who disagree with them",
		picture: "https://www.astrology-zodiac-signs.com/images/aquarius.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/aquarius/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/aquarius/",
        sumary: "Aquarius-born are shy and quiet , but on the other hand they can be eccentric and energetic. However, in both cases, they are deep thinkers and highly intellectual people who love helping others. They are able to see without prejudice, on both sides, which makes them people who can easily solve problems. Although they can easily adapt to the energy that surrounds them, Aquarius-born have a deep need to be some time alone and away from everything, in order to restore power. People born under the Aquarius sign, look at the world as a place full of possibilities.",
		zodiacId: "11"
    },
    {
        zodiacname: "Pisces",
        symbol: "Fish",
        element: "Water",
        color: "Mauve, Lilac, Purple, Violet, Sea green",
        Day: "Thursday",
        Ruler: "Neptune, Jupiter",
        compatibility: "Virgo, Taurus",
        luckyNumbers: "  3, 9, 12, 15, 18, 24",
        strengths: "  Compassionate, artistic, intuitive, gentle, wise, musical",
        weaknesses: " Fearful, overly trusting, sad, desire to escape reality, can be a victim or a martyr",
        likes: "  Being alone, sleeping, music, romance, visual media, swimming, spiritual themes",
        dislikes: " Know-it-all, being criticized, the past coming back to haunt, cruelty of any kind",
		picture: "https://www.astrology-zodiac-signs.com/images/pisces.jpg",
        readmore: "https://www.astrology-zodiac-signs.com/zodiac-signs/pisces/",
        daily: "https://www.astrology-zodiac-signs.com/horoscope/pisces/",
        sumary: "Pisces are very friendly, so they often find themselves in a company of very different people. Pisces are selfless, they are always willing to help others, without hoping to get anything back. is a Water sign and as such this zodiac sign is characterized by empathy and expressed emotional capacity.",
		zodiacId: "12"
    }


];
export default (n = 12) => 
    Promise.resolve(zodiac.sort(() => 0.5 -Math.random()).slice(0, n));